#!/bin/bash
#
# $Id$
#
# Convert a BSDL file to a jtag part description
#
# Copyright (C) 2009, A. Laeuger
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
# 02111-1307, USA.
#

scriptname=`basename $0`

function usage ()
{
    cat <<EOF
Usage:	$scriptname <bsdl-file> <jtag-file>
Converts a BSDL file to a jtag part description.

Parameters
  bsdl-file :  Name of BSDL file
  jtag-file :  Name of converted jtag description file

EOF
}

if [[ -z $1 || -z $2 ]]; then
    usage
    exit 1
fi


echo "bsdl dump $1" | jtag > $2

exit 0
