.TH bsdl2jtag 1 "April 7, 2009" UrJTAG
.SH NAME
bsdl2jtag \- UrJTAG declaration file conversion
.SH SYNOPSIS
.B bsdl2jtag
.I bsdlfile
.I jtagfile
.SH DESCRIPTION
.B bsdl2jtag
converts BSDL files to JTAG files which can be used by
.BR jtag (1).
.B bsdl2jtag
reads from
.I bsdlfile
and produces its output in the file
.IR jtagfile .
.SH OPTIONS
None.
.SH BUGS
Bugs are tracked at the project homepage, http://www.urjtag.org
.SH "SEE ALSO"
.BR jtag (1)
.SH AUTHORS
Authors and contributors are listed in the AUTHORS and THANKS files in
the source documentation.
.SH HISTORY
JTAG Tools originally have been developed as part of the openwince project by
Marcel Telka. They became an independent project named UrJTAG in late 2007.

