.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH jtag 1 "OCTOBER 2003" Linux "User Manuals"
.SH NAME
jtag \- bsdl2jtag
.SH SYNOPSIS
.B bsdl2jtag 
.SH DESCRIPTION
.B bsdl2jtag converts bsdl files to jtag files which can be used by B jtag. .B bsdl2jtag reads from stdin and produces its output on stdout.
.SH OPTIONS
none
.SH FILES
none
.SH BUGS
Lots
.SH AUTHOR
Marcel Telka <marcel@telka.sk>
.SH "SEE ALSO"
.BR jtag (1)



