.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH jtag 1 "OCTOBER 2003" Linux "User Manuals"
.SH NAME
jtag \- jtag manipulation tool
.SH SYNOPSIS
.B jtag 
.I file
.B ...
.SH DESCRIPTION
JTAG Tools is a software package which enables working with JTAG-aware
(IEEE 1149.1) hardware devices (parts) and boards through JTAG adapter.

.SH OPTIONS
none
.SH FILES
.I /usr/share/jtag
.RS
Scripts for various controllers
.SH BUGS
Lots
.SH AUTHOR
Marcel Telka <marcel@telka.sk>
.SH "SEE ALSO"
.BR bsdl2jtag (1)



